export const people = [{"id":0,"firstName":"Bill","name":"Bill","student":true,"age":1,"city":"Manchester","country":"uk","email":"bill@manchester.uk","birthDate":"2021-12-21"},
{"id":1,"firstName":"Mary","name":"Mary","age":22,"student":true,"city":"New York","country":"usa","email":"mary.mary@gmail.com","birthDate":"1982-11-30"},
{"id":2,"firstName":"John","name":"John","age":32,"student":false,"city":"London","country":"uk","email":"john@London.com","birthDate":"1970-12-01"},
{"id":3,"firstName":"Boby","name":"Boby","age":12,"student":false,"city":"Vancouver","country":"ca","email":"boby@vancouver.com","birthDate":"1987-12-02"},
{"id":4,"firstName":"Billy","name":"Billy","age":32,"student":false,"city":"Edmonton","email":"billy@edmonton.ca","country":"ca","birthDate":"1990-12-03"},
{"id":5,"firstName":"Johny","name":"Johny","age":14,"student":true,"city":"San Jose","country":"usa","email":"johny@yahoo.com","birthDate":"1989-12-04"},
{"id":6,"firstName":"Hilly","name":"Hilly","age":32,"student":true,"city":"London","country":"uk","email":"hilly@london.co.uk","birthDate":"2010-12-05"},
{"id":7,"firstName":"Hillaay","name":"Hillaay","age":47,"student":false,"city":"Bristol","country":"uk","email":"hillaay@britain.com","birthDate":"1987-12-06"},
{"id":8,"firstName":"Matthew","name":"Matthew","age":47,"student":false,"city":"Leeds","country":"uk","email":"matthew@leeds.co.uk","birthDate":"2007-12-07"},
{"id":9,"firstName":"David","name":"David","age":48,"student":false,"city":"Toronto","country":"ca","email":"david@toronto.com","birthDate":"1979-12-08 "},
{"id":10,"firstName":"Richard","name":"Richard","age":9,"student":false,"city":"Ottawa","country":"ca","email":"richard@ottawa.ca","birthDate":"2000-12-09"},
{"id":11,"firstName":"Hillary","name":"Hillary","age":34,"student":true,"city":"Los Angeles","email":"hillary@gmail.com","country":"usa","birthDate":"1982-12-10"},
{"id":12,"firstName":"Maria","name":"Williams","age":32,"student":true,"city":"New York","email":"maria@gmail.com","country":"usa","birthDate":"1981-12-11"},
{"id":13,"firstName":"Billa","name":"Bill","student":true,"age":20,"city":"Manchester","country":"uk","email":"bill@manchester.uk","birthDate":"1980-11-29"},
{"id":14,"firstName":"Marius","name":"Mary","age":22,"student":true,"city":"New York","country":"usa","email":"mary.mary@gmail.com","birthDate":"1982-11-30"},
{"id":15,"firstName":"John","name":"John","age":2,"student":false,"city":"London","country":"uk","email":"john@London.com","birthDate":"1970-12-01"},
{"id":16,"firstName":"Boby","name":"Boby","age":11,"student":false,"city":"Vancouver","country":"ca","email":"boby@vancouver.com","birthDate":"1987-12-02"},
{"id":17,"firstName":"Billy","name":"Billy","age":12,"student":false,"city":"Edmonton","email":"billy@edmonton.ca","country":"ca","birthDate":"1990-12-03"},
{"id":18,"firstName":"Johny","name":"Johny","age":4,"student":true,"city":"San Jose","country":"usa","email":"johny@yahoo.com","birthDate":"1989-12-04"},
{"id":19,"firstName":"Hilly","name":"Hilly","age":56,"student":true,"city":"London","country":"uk","email":"hilly@london.co.uk","birthDate":"2010-12-05"},
{"id":20,"firstName":"Hillaay","name":"Hillaay","age":47,"student":false,"city":"Bristol","country":"uk","email":"hillaay@britain.com","birthDate":"1987-12-06"},
{"id":21,"firstName":"Matthew","name":"Matthew","age":27,"student":false,"city":"Leeds","country":"uk","email":"matthew@leeds.co.uk","birthDate":"2007-12-07"},
{"id":22,"firstName":"David","name":"David","age":48,"student":false,"city":"Toronto","country":"ca","email":"david@toronto.com","birthDate":"1979-12-08 "},
{"id":21,"firstName":"Richard","name":"Richard","age":9,"student":false,"city":"Ottawa","country":"ca","email":"richard@ottawa.ca","birthDate":"2000-12-09"},
{"id":22,"firstName":"Hillary","name":"Hillary","age":16,"student":true,"city":"Los Angeles","email":"hillary@gmail.com","country":"usa","birthDate":"1982-12-10"},
{"id":23,"firstName":"Maria","name":"Williams <button>button</button>","age":17,"student":true,"city":"New York","email":"maria@gmail.com","country":"usa","birthDate":"1981-12-11"}];